#!/bin/bash

for i in {0..9} {a..f}; do
    for j in {0..9} {a..f}; do
        ip -6 neigh add proxy 2001:da8:d800:f001:160:99:1:$i$j dev eth0
        ip -6 neigh add proxy 2001:da8:d800:f001:176:99:1:$i$j dev eth0
    done
done

exit 0
