#!/bin/sh

ip link set eth0 up
ip link set eth1 up
ip route replace 202.141.160.0/25 dev eth0 proto kernel scope link
ip route replace 202.141.176.0/25 dev eth1 proto kernel scope link

ip route replace 202.141.160.0/25 dev eth0 table 1000
ip route replace default via 202.141.160.126 table 1000
ip rule del fwmark 160 lookup 1000 pref 2999 2>/dev/null
ip rule add fwmark 160 lookup 1000 pref 2999

ip route replace 202.141.176.0/25 dev eth1 table 1001
ip route replace default via 202.141.176.126 table 1001
ip rule del fwmark 176 lookup 1001 pref 2999 2>/dev/null
ip rule add fwmark 176 lookup 1001 pref 2999

ip route replace 202.141.160.0/25 dev eth0 table 10000
ip route replace 202.141.176.0/25 dev eth1 table 10000

ip rule del lookup 1002 pref 1000 2>/dev/null
ip rule add lookup 1002 pref 1000

ip rule del pref 1001 lookup main 2>/dev/null
ip rule add pref 1001 to 10.4.0.0/16 lookup main

ip route replace 10.6.0.0/16 via 10.6.0.1 table 10000
ip route replace 10.9.0.0/16 via 10.9.0.1 table 10000
ip route replace 10.10.0.0/16 via 10.10.0.1 table 10000
ip route replace 10.11.0.0/16 via 10.11.0.1 table 10000

ip route replace 10.0.7.0/30 dev blog-sg table 10000
ip route replace 10.0.9.0/30 dev yfgao-do table 10000
ip route replace 10.0.10.0/30 dev do table 10000
ip route replace 10.0.11.0/30 dev armnotstrong table 10000

ip rule del from all lookup 10000 pref 10000 2>/dev/null
ip rule add from all lookup 10000 pref 10000

ip route replace default via 10.0.10.1 table 1003
ip rule del fwmark 1194 lookup 1003 pref 2999 2>/dev/null
ip rule add fwmark 1194 lookup 1003 pref 2999

ip route replace default via 10.0.9.1 table 1004
ip rule del fwmark 1195 lookup 1004 pref 2999 2>/dev/null
ip rule add fwmark 1195 lookup 1004 pref 2999

ip -6 addr add 2001:da8:d800:f001:202:141:160:95/64 dev eth0
ip -6 route add 2001:da8:d800:f001::/64 dev eth0
ip -6 route add default via 2001:da8:d800:f001::1 dev eth0

ip -6 route add 2001:da8:d800:f001::/64 dev eth0 table 1000
ip -6 route add default via 2001:da8:d800:f001::1 dev eth0 table 1000
ip -6 rule del fwmark 95 lookup 1000 pref 1000
ip -6 rule add fwmark 95 lookup 1000 pref 1000

ip -6 rule del from all lookup 1002 pref 1000 2>/dev/null
# this is to ensure local subnet do not go through gateway
ip -6 route add 2001:da8:d800:f001::/64 dev eth0 table 1002 2>/dev/null
ip -6 rule add from all lookup 1002 pref 1000

ip -6 route replace default via fdfe:dcba:9876::10:1 table 1003
ip -6 rule del fwmark 1194 lookup 1003 pref 2999 2>/dev/null
ip -6 rule add fwmark 1194 lookup 1003 pref 2999

ip -6 route replace default via fdfe:dcba:9876::9:1 table 1004
ip -6 rule del fwmark 1195 lookup 1004 pref 2999 2>/dev/null
ip -6 rule add fwmark 1195 lookup 1004 pref 2999

exit 0
