#!/bin/sh

ip link set eth0 up
ip link set eth1 up
ip route replace 202.141.160.0/25 dev eth0 proto kernel scope link
ip route replace 202.141.176.0/25 dev eth1 proto kernel scope link

ip route add 202.141.160.0/25 dev eth0 table 1000
ip route add default via 202.141.160.126 dev eth0 table 1000
ip route add 202.141.176.0/25 dev eth1 table 1001
ip route add default via 202.141.176.126 dev eth1 table 1001

ip route replace default via 202.141.160.126 table 1000
ip rule del fwmark 160 lookup 1000 pref 2999 2>/dev/null
ip rule add fwmark 160 lookup 1000 pref 2999

ip route replace default via 202.141.176.126 table 1001
ip rule del fwmark 176 lookup 1001 pref 2999 2>/dev/null
ip rule add fwmark 176 lookup 1001 pref 2999

ip route replace 10.8.0.0/16 via 10.8.0.2 table 1002
ip route replace 10.7.0.0/16 via 10.7.0.2 table 1002
ip route replace 10.6.0.0/16 via 10.6.0.2 table 1002
ip rule del from all lookup 1002 pref 2000 2>/dev/null
ip rule add from all lookup 1002 pref 2000

ip route replace default via 10.0.2.1 table 1003
ip rule del fwmark 1194 lookup 1003 pref 2999 2>/dev/null
ip rule add fwmark 1194 lookup 1003 pref 2999

ip route replace default via 10.0.9.1 table 1004
ip rule del fwmark 1195 lookup 1004 pref 2999 2>/dev/null
ip rule add fwmark 1195 lookup 1004 pref 2999

ip -6 addr add 2001:da8:d800:f001:202:141:160:95/64 dev eth0
ip -6 route add 2001:da8:d800:f001::/64 dev eth0
ip -6 route add default via 2001:da8:d800:f001::1 dev eth0

ip -6 route add 2001:da8:d800:f001::/64 dev eth0 table 1000
ip -6 route add default via 2001:da8:d800:f001::1 dev eth0 table 1000
ip -6 rule del fwmark 95 lookup 1000 pref 1000
ip -6 rule add fwmark 95 lookup 1000 pref 1000

ip -6 route replace default via fdfe:dcba:9876::2:1 table 1003
ip -6 rule del fwmark 1194 lookup 1003 pref 2999 2>/dev/null
ip -6 rule add fwmark 1194 lookup 1003 pref 2999

ip -6 route replace default via fdfe:dcba:9876::9:1 table 1004
ip -6 rule del fwmark 1195 lookup 1004 pref 2999 2>/dev/null
ip -6 rule add fwmark 1195 lookup 1004 pref 2999

exit 0
