#!/bin/bash

CONF_DIR=/home/boj/smartproxy/conf
pushd $CONF_DIR >/dev/null
if [ ! -f "USTC.txt" ]; then
    echo "CIDR files not exist"
    exit 1
fi

function set_route() {
    ip route flush table $2
    while read prefix comment; do
        if [[ "$prefix" =~ ^[0-9.]+(/[0-9]+)?$ ]]; then
            ip route add $prefix via $1 table $2
        fi
    done
}

function replace_route() {
    while read prefix comment; do
        if [[ "$prefix" =~ ^[0-9.]+(/[0-9]+)?$ ]]; then
            ip route replace $prefix via $1 table $2
        fi
    done
}

# set up IP-in-IP tunnel
ip tunnel del tunipip
ip tunnel add tunipip mode ipip local 202.141.160.99 remote 202.38.95.110
ip link set tunipip up
ip addr add 10.38.160.99/32 dev tunipip
ip route replace 10.38.95.110/32 dev tunipip

ip tunnel del tunipip2
ip tunnel add tunipip2 mode ipip local 202.141.176.99 remote 202.141.176.110
ip link set tunipip2 up
ip addr add 10.141.176.99/32 dev tunipip2
ip route replace 10.141.176.110/32 dev tunipip2

# define routing table preference (high to low)
route_pref="mirrors_mobile ustc cernet mobile telecom chnroutes whitelist blocked"

counter=10000
for i in $route_pref; do
    counter=$(($counter+1))
    eval $i=$counter
done

# generate routing tables
cat mirrors-mobile.txt | set_route 10.141.176.110 $mirrors_mobile
cat USTC.txt | set_route 202.141.160.126 $ustc
cat CHINANET.txt CNC.txt google.txt | set_route 202.141.160.126 $telecom
cat CMCC.txt | set_route 202.141.176.126 $mobile
cat CERNET.txt | set_route 10.38.95.110 $cernet
cat chnroutes.txt abroad-telecom.txt | set_route 202.141.160.126 $chnroutes
cat local-whitelist.txt | set_route 202.141.176.126 $whitelist
cat blocked-ip.txt | replace_route 10.13.0.1 $blocked

# set up ip rule
counter=10000
for i in $route_pref; do
    counter=$(($counter+1))
    origpref=$(ip rule | grep "from all lookup $counter" | awk 'BEGIN{FS=":"}{print $1}')
    if [ ! -z "$origpref" ]; then
        ip rule del from all lookup $counter pref $origpref
    fi
    ip rule add from all lookup $counter pref $counter
done

while true; do
    counter=$(($counter+1))
    origpref=$(ip rule | grep "from all lookup $counter" | awk 'BEGIN{FS=":"}{print $1}')
    [ -z "$origpref" ] && break
    ip rule del from all lookup $counter pref $origpref
done

# default for abroad route
ip route replace default via 202.141.176.126

# IPv6 route
cat chnroutes-v6.txt | while read prefix comment; do
    ip -6 route add $prefix via 2001:da8:d800:f001::1    2>/dev/null
done

popd >/dev/null
#IPV6_SCRIPT=$(dirname $0)/ipv6-tun2socks
#if [ -x "$IPV6_SCRIPT" ]; then
#    $IPV6_SCRIPT
#    cat $CONF_DIR/blacklist-v6.txt | while read prefix comment; do
#        ip -6 route add unreachable $prefix 2>/dev/null
#    done
#else
#    ip -6 route add unreachable 2000::/3    2>/dev/null
#fi

exit 0
