#!/bin/bash
# for proxy client
# proxy client and server must be in one subnet (layer-2 connected)

LOCALIP=202.141.160.99
GATEWAY=202.141.160.126
DEV=eth0
PROXYIP=202.141.176.110

if [ `whoami` != 'root' ]; then
    echo "This script should be run by root!"
    exit 1
fi
cd `dirname $0`

# Inbound traffic should be replyed through the same interface
ip route replace default via $GATEWAY dev $DEV table 16099
if [ $(ip rule | grep "from $LOCALIP lookup 16099" | wc -l) -eq 0 ]; then
    ip rule add from $LOCALIP lookup 16099
fi

# CERNET and China Telecom go through default gateway
cat conf/CERNET.txt conf/CHINANET.txt | \
while read prefix; do
    ip route replace $prefix via $GATEWAY dev $DEV
done

# Direct route to proxy server (requires layer-2 connectivity)
ip route replace $PROXYIP/32 dev $DEV

# The default route is proxy
ip route replace default via $PROXYIP dev $DEV
